name: Build, deploy

on:
 push:
  branches: [master,main]

jobs: 
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
    
      - name: Install dependencies
        run: |
          pip install requirements.txt
    
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
    
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply